Repository jdu211171/schedule-website, pull requests merged in 2025-04, with the labels that each got.

#31 master-pagination
  .gitignore
  bun.lock
  deno.lock
  package.json
  prisma/seed.ts
  src/actions/booth/index.ts
  src/actions/classType/index.ts
  src/actions/count.ts
  src/actions/evaluation/index.ts
  src/actions/grade/index.ts
  src/actions/student/index.ts
  src/actions/subject/index.ts
  src/actions/subjectType/index.ts
  src/actions/teacher/index.ts
  src/actions/teacherSubject/index.ts
  src/components/booth/booth-table.tsx
  src/components/class/class-table.tsx
  src/components/data-table.tsx
  src/components/evaluation/evaluation-table.tsx
  src/components/grade/grade-table.tsx
  src/components/student/student-form-dialog.tsx
  src/components/student/student-table.tsx
  src/components/subject-type/subject-type-table.tsx
  src/components/subject/subject-table.tsx
  src/components/ui/pagination.tsx
  src/components/ui/select.tsx
  src/hooks/useBoothQuery.ts
  src/hooks/useClassTypeQuery.ts
  src/hooks/useEvaluationQuery.ts
  src/hooks/useGradeQuery.ts
  src/hooks/useStudentQuery.ts
  src/hooks/useSubjectQuery.ts
  src/hooks/useSubjectTypeQuery.ts
  src/hooks/useTeacherQuery.ts
  src/hooks/useTeacherSubjectQuery.ts
  src/schemas/student.schema.ts
Labels: bug, enhancement

#33 Update orderBy clause to sort by createdAt in multiple findMany queries
  src/actions/booth/index.ts
  src/actions/classType/index.ts
  src/actions/evaluation/index.ts
  src/actions/grade/index.ts
  src/actions/student/index.ts
  src/actions/subject/index.ts
  src/actions/subjectType/index.ts
  src/actions/teacher/index.ts
  src/actions/teacherSubject/index.ts
Labels: enhancement

#38 Add teacher management functionality with creation, editing, and deletion features
  src/app/dashboard/master/tabs-nav.tsx
  src/app/dashboard/master/teacher/page.tsx
  src/components/teacher/teacher-form-dialog.tsx
  src/components/teacher/teacher-table.tsx
  src/components/teacher/teacher-tabs.tsx
  src/hooks/useTeacherQuery.ts
Labels: bug, enhancement

#40 gone back to auth.js
  .env.example
  bun.lock
  package.json
  prisma/migrations/20250417071046_back_to_auth_js/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/actions/auth-actions.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/auth/callback/route.ts
  src/app/auth/login/page.tsx
  src/app/dashboard/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/auth.config.ts
  src/auth.ts
  src/components/grade/grade-form-dialog.tsx
  src/components/login-form.tsx
  src/components/user-profile-menu.tsx
  src/lib/supabase/client.ts
  src/lib/supabase/context/AuthContext.tsx
  src/lib/supabase/middleware.ts
  src/lib/supabase/server.ts
  src/middleware.ts
Labels: documentation, enhancement
